[tool.poetry]
name = "simple-rc4-py"
version = "0.1.0"
description = "ğŸ‚ğŸ‚ğŸ‚ Pythonã§RC4æš—å·ã‚’å®Ÿè£…ã—ã¦ã¿ãŸï¼"
authors = ["osawa-koki <koki@osawa.dev>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "simple_rc4"}]

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
